fragment AccommodationParts on Accommodation {
  __typename
  slug
  title
  description
  hero {
    __typename
    mobileSrc
    desktopSrc
  }
  gallery {
    __typename
    src
    alt
    fullSize
  }
  imagesPerPage
  cardImage
  cardMobileImage
  cardDescription
  cardFeatures
  showBookNow
  infoSections {
    __typename
    heading
    content
    align
  }
  cta {
    __typename
    heading
    description
    button {
      __typename
      href
      label
    }
  }
}

fragment AdventuresParts on Adventures {
  __typename
  slug
  title
  description
  category
  hero {
    __typename
    mobileSrc
    desktopSrc
  }
  gallery {
    __typename
    src
    alt
    fullSize
  }
  imagesPerPage
  cardImage
  cardMobileImage
  cardDescription
  cardFeatures
  infoSections {
    __typename
    heading
    content
    align
  }
  cta {
    __typename
    heading
    description
    button {
      __typename
      href
      label
    }
  }
}

fragment ListingPagesParts on ListingPages {
  __typename
  title
  description
  hero {
    __typename
    mobileSrc
    desktopSrc
  }
  items {
    __typename
    image
    href
    blocks {
      __typename
      ... on ListingPagesItemsBlocksTitle {
        content
      }
      ... on ListingPagesItemsBlocksText {
        content
      }
      ... on ListingPagesItemsBlocksSubheading {
        content
      }
      ... on ListingPagesItemsBlocksList {
        contentItems
      }
    }
  }
  columns
  showBookNow
  infoSections {
    __typename
    heading
    content
    align
  }
  cta {
    __typename
    heading
    description
    button {
      __typename
      href
      label
    }
  }
  footnote
  galleryHeading
}

fragment ContactPageParts on ContactPage {
  __typename
  title
  mobileSrc
  desktopSrc
  infoHeading
  infoSections {
    __typename
    sectionTitle
    sectionsItems
  }
  formHeading
  formFields {
    __typename
    name
    label
    type
    placeholder
    required
  }
  formSubmitLabel
}

fragment GalleryPageParts on GalleryPage {
  __typename
  galleryHeading
  galleryDetail
  emptyMessage
}

fragment SiteParts on Site {
  __typename
  address
  phone
  email
  social {
    __typename
    facebook
    instagram
    youtube
  }
  seo {
    __typename
    defaultTitle
    defaultDescription
    home {
      __typename
      title
      description
    }
  }
  errors {
    __typename
    generic {
      __typename
      title
      message
      button
    }
    gallery {
      __typename
      title
      message
      button
    }
  }
  defaults {
    __typename
    galleryHeading
  }
}

fragment NavParts on Nav {
  __typename
  topLevelLinks {
    __typename
    href
    label
  }
  accommodationLinks {
    __typename
    href
    label
  }
  adventureLinks {
    __typename
    href
    label
  }
}
