//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  accommodation: Accommodation;
  accommodationConnection: AccommodationConnection;
  adventures: Adventures;
  adventuresConnection: AdventuresConnection;
  listingPages: ListingPages;
  listingPagesConnection: ListingPagesConnection;
  contactPage: ContactPage;
  contactPageConnection: ContactPageConnection;
  galleryPage: GalleryPage;
  galleryPageConnection: GalleryPageConnection;
  site: Site;
  siteConnection: SiteConnection;
  nav: Nav;
  navConnection: NavConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAccommodationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAccommodationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AccommodationFilter>;
};


export type QueryAdventuresArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAdventuresConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AdventuresFilter>;
};


export type QueryListingPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryListingPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ListingPagesFilter>;
};


export type QueryContactPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactPageFilter>;
};


export type QueryGalleryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGalleryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryPageFilter>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QueryNavArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavFilter>;
};

export type DocumentFilter = {
  accommodation?: InputMaybe<AccommodationFilter>;
  adventures?: InputMaybe<AdventuresFilter>;
  listingPages?: InputMaybe<ListingPagesFilter>;
  contactPage?: InputMaybe<ContactPageFilter>;
  galleryPage?: InputMaybe<GalleryPageFilter>;
  site?: InputMaybe<SiteFilter>;
  nav?: InputMaybe<NavFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Accommodation | Adventures | ListingPages | ContactPage | GalleryPage | Site | Nav | Folder;

export type AccommodationHero = {
  __typename?: 'AccommodationHero';
  mobileSrc: Scalars['String']['output'];
  desktopSrc: Scalars['String']['output'];
};

export type AccommodationGallery = {
  __typename?: 'AccommodationGallery';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  fullSize?: Maybe<Scalars['String']['output']>;
};

export type AccommodationInfoSections = {
  __typename?: 'AccommodationInfoSections';
  heading: Scalars['String']['output'];
  content?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  align?: Maybe<Scalars['String']['output']>;
};

export type AccommodationCtaButton = {
  __typename?: 'AccommodationCtaButton';
  href?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type AccommodationCta = {
  __typename?: 'AccommodationCta';
  heading: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  button?: Maybe<AccommodationCtaButton>;
};

export type Accommodation = Node & Document & {
  __typename?: 'Accommodation';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  hero?: Maybe<AccommodationHero>;
  gallery?: Maybe<Array<Maybe<AccommodationGallery>>>;
  imagesPerPage?: Maybe<Scalars['Float']['output']>;
  cardImage?: Maybe<Scalars['String']['output']>;
  cardMobileImage?: Maybe<Scalars['String']['output']>;
  cardDescription?: Maybe<Scalars['String']['output']>;
  cardFeatures?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  showBookNow?: Maybe<Scalars['Boolean']['output']>;
  infoSections?: Maybe<Array<Maybe<AccommodationInfoSections>>>;
  cta?: Maybe<AccommodationCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AccommodationHeroFilter = {
  mobileSrc?: InputMaybe<ImageFilter>;
  desktopSrc?: InputMaybe<ImageFilter>;
};

export type AccommodationGalleryFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  fullSize?: InputMaybe<ImageFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AccommodationInfoSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  align?: InputMaybe<StringFilter>;
};

export type AccommodationCtaButtonFilter = {
  href?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type AccommodationCtaFilter = {
  heading?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  button?: InputMaybe<AccommodationCtaButtonFilter>;
};

export type AccommodationFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  hero?: InputMaybe<AccommodationHeroFilter>;
  gallery?: InputMaybe<AccommodationGalleryFilter>;
  imagesPerPage?: InputMaybe<NumberFilter>;
  cardImage?: InputMaybe<ImageFilter>;
  cardMobileImage?: InputMaybe<ImageFilter>;
  cardDescription?: InputMaybe<StringFilter>;
  cardFeatures?: InputMaybe<StringFilter>;
  showBookNow?: InputMaybe<BooleanFilter>;
  infoSections?: InputMaybe<AccommodationInfoSectionsFilter>;
  cta?: InputMaybe<AccommodationCtaFilter>;
};

export type AccommodationConnectionEdges = {
  __typename?: 'AccommodationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Accommodation>;
};

export type AccommodationConnection = Connection & {
  __typename?: 'AccommodationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AccommodationConnectionEdges>>>;
};

export type AdventuresHero = {
  __typename?: 'AdventuresHero';
  mobileSrc: Scalars['String']['output'];
  desktopSrc: Scalars['String']['output'];
};

export type AdventuresGallery = {
  __typename?: 'AdventuresGallery';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  fullSize?: Maybe<Scalars['String']['output']>;
};

export type AdventuresInfoSections = {
  __typename?: 'AdventuresInfoSections';
  heading: Scalars['String']['output'];
  content?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  align?: Maybe<Scalars['String']['output']>;
};

export type AdventuresCtaButton = {
  __typename?: 'AdventuresCtaButton';
  href?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type AdventuresCta = {
  __typename?: 'AdventuresCta';
  heading: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  button?: Maybe<AdventuresCtaButton>;
};

export type Adventures = Node & Document & {
  __typename?: 'Adventures';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  hero?: Maybe<AdventuresHero>;
  gallery?: Maybe<Array<Maybe<AdventuresGallery>>>;
  imagesPerPage?: Maybe<Scalars['Float']['output']>;
  cardImage?: Maybe<Scalars['String']['output']>;
  cardMobileImage?: Maybe<Scalars['String']['output']>;
  cardDescription?: Maybe<Scalars['String']['output']>;
  cardFeatures?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  infoSections?: Maybe<Array<Maybe<AdventuresInfoSections>>>;
  cta?: Maybe<AdventuresCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AdventuresHeroFilter = {
  mobileSrc?: InputMaybe<ImageFilter>;
  desktopSrc?: InputMaybe<ImageFilter>;
};

export type AdventuresGalleryFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  fullSize?: InputMaybe<ImageFilter>;
};

export type AdventuresInfoSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  align?: InputMaybe<StringFilter>;
};

export type AdventuresCtaButtonFilter = {
  href?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type AdventuresCtaFilter = {
  heading?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  button?: InputMaybe<AdventuresCtaButtonFilter>;
};

export type AdventuresFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  hero?: InputMaybe<AdventuresHeroFilter>;
  gallery?: InputMaybe<AdventuresGalleryFilter>;
  imagesPerPage?: InputMaybe<NumberFilter>;
  cardImage?: InputMaybe<ImageFilter>;
  cardMobileImage?: InputMaybe<ImageFilter>;
  cardDescription?: InputMaybe<StringFilter>;
  cardFeatures?: InputMaybe<StringFilter>;
  infoSections?: InputMaybe<AdventuresInfoSectionsFilter>;
  cta?: InputMaybe<AdventuresCtaFilter>;
};

export type AdventuresConnectionEdges = {
  __typename?: 'AdventuresConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Adventures>;
};

export type AdventuresConnection = Connection & {
  __typename?: 'AdventuresConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AdventuresConnectionEdges>>>;
};

export type ListingPagesHero = {
  __typename?: 'ListingPagesHero';
  mobileSrc: Scalars['String']['output'];
  desktopSrc: Scalars['String']['output'];
};

export type ListingPagesItemsBlocksTitle = {
  __typename?: 'ListingPagesItemsBlocksTitle';
  content?: Maybe<Scalars['String']['output']>;
};

export type ListingPagesItemsBlocksText = {
  __typename?: 'ListingPagesItemsBlocksText';
  content?: Maybe<Scalars['String']['output']>;
};

export type ListingPagesItemsBlocksSubheading = {
  __typename?: 'ListingPagesItemsBlocksSubheading';
  content?: Maybe<Scalars['String']['output']>;
};

export type ListingPagesItemsBlocksList = {
  __typename?: 'ListingPagesItemsBlocksList';
  contentItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ListingPagesItemsBlocks = ListingPagesItemsBlocksTitle | ListingPagesItemsBlocksText | ListingPagesItemsBlocksSubheading | ListingPagesItemsBlocksList;

export type ListingPagesItems = {
  __typename?: 'ListingPagesItems';
  image?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  blocks?: Maybe<Array<Maybe<ListingPagesItemsBlocks>>>;
};

export type ListingPagesInfoSections = {
  __typename?: 'ListingPagesInfoSections';
  heading: Scalars['String']['output'];
  content?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  align?: Maybe<Scalars['String']['output']>;
};

export type ListingPagesCtaButton = {
  __typename?: 'ListingPagesCtaButton';
  href?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type ListingPagesCta = {
  __typename?: 'ListingPagesCta';
  heading: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  button?: Maybe<ListingPagesCtaButton>;
};

export type ListingPages = Node & Document & {
  __typename?: 'ListingPages';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  hero?: Maybe<ListingPagesHero>;
  items?: Maybe<Array<Maybe<ListingPagesItems>>>;
  columns?: Maybe<Scalars['Float']['output']>;
  showBookNow?: Maybe<Scalars['Boolean']['output']>;
  infoSections?: Maybe<Array<Maybe<ListingPagesInfoSections>>>;
  cta?: Maybe<ListingPagesCta>;
  footnote?: Maybe<Scalars['String']['output']>;
  galleryHeading?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ListingPagesHeroFilter = {
  mobileSrc?: InputMaybe<ImageFilter>;
  desktopSrc?: InputMaybe<ImageFilter>;
};

export type ListingPagesItemsBlocksTitleFilter = {
  content?: InputMaybe<StringFilter>;
};

export type ListingPagesItemsBlocksTextFilter = {
  content?: InputMaybe<StringFilter>;
};

export type ListingPagesItemsBlocksSubheadingFilter = {
  content?: InputMaybe<StringFilter>;
};

export type ListingPagesItemsBlocksListFilter = {
  contentItems?: InputMaybe<StringFilter>;
};

export type ListingPagesItemsBlocksFilter = {
  title?: InputMaybe<ListingPagesItemsBlocksTitleFilter>;
  text?: InputMaybe<ListingPagesItemsBlocksTextFilter>;
  subheading?: InputMaybe<ListingPagesItemsBlocksSubheadingFilter>;
  list?: InputMaybe<ListingPagesItemsBlocksListFilter>;
};

export type ListingPagesItemsFilter = {
  image?: InputMaybe<ImageFilter>;
  href?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<ListingPagesItemsBlocksFilter>;
};

export type ListingPagesInfoSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
  align?: InputMaybe<StringFilter>;
};

export type ListingPagesCtaButtonFilter = {
  href?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type ListingPagesCtaFilter = {
  heading?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  button?: InputMaybe<ListingPagesCtaButtonFilter>;
};

export type ListingPagesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  hero?: InputMaybe<ListingPagesHeroFilter>;
  items?: InputMaybe<ListingPagesItemsFilter>;
  columns?: InputMaybe<NumberFilter>;
  showBookNow?: InputMaybe<BooleanFilter>;
  infoSections?: InputMaybe<ListingPagesInfoSectionsFilter>;
  cta?: InputMaybe<ListingPagesCtaFilter>;
  footnote?: InputMaybe<StringFilter>;
  galleryHeading?: InputMaybe<StringFilter>;
};

export type ListingPagesConnectionEdges = {
  __typename?: 'ListingPagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ListingPages>;
};

export type ListingPagesConnection = Connection & {
  __typename?: 'ListingPagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ListingPagesConnectionEdges>>>;
};

export type ContactPageInfoSections = {
  __typename?: 'ContactPageInfoSections';
  sectionTitle?: Maybe<Scalars['String']['output']>;
  sectionsItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ContactPageFormFields = {
  __typename?: 'ContactPageFormFields';
  name?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  placeholder?: Maybe<Scalars['String']['output']>;
  required?: Maybe<Scalars['Boolean']['output']>;
};

export type ContactPage = Node & Document & {
  __typename?: 'ContactPage';
  title?: Maybe<Scalars['String']['output']>;
  mobileSrc?: Maybe<Scalars['String']['output']>;
  desktopSrc?: Maybe<Scalars['String']['output']>;
  infoHeading?: Maybe<Scalars['String']['output']>;
  infoSections?: Maybe<Array<Maybe<ContactPageInfoSections>>>;
  formHeading?: Maybe<Scalars['String']['output']>;
  formFields?: Maybe<Array<Maybe<ContactPageFormFields>>>;
  formSubmitLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactPageInfoSectionsFilter = {
  sectionTitle?: InputMaybe<StringFilter>;
  sectionsItems?: InputMaybe<StringFilter>;
};

export type ContactPageFormFieldsFilter = {
  name?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<StringFilter>;
  required?: InputMaybe<BooleanFilter>;
};

export type ContactPageFilter = {
  title?: InputMaybe<StringFilter>;
  mobileSrc?: InputMaybe<ImageFilter>;
  desktopSrc?: InputMaybe<ImageFilter>;
  infoHeading?: InputMaybe<StringFilter>;
  infoSections?: InputMaybe<ContactPageInfoSectionsFilter>;
  formHeading?: InputMaybe<StringFilter>;
  formFields?: InputMaybe<ContactPageFormFieldsFilter>;
  formSubmitLabel?: InputMaybe<StringFilter>;
};

export type ContactPageConnectionEdges = {
  __typename?: 'ContactPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ContactPage>;
};

export type ContactPageConnection = Connection & {
  __typename?: 'ContactPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactPageConnectionEdges>>>;
};

export type GalleryPage = Node & Document & {
  __typename?: 'GalleryPage';
  galleryHeading?: Maybe<Scalars['String']['output']>;
  galleryDetail?: Maybe<Scalars['String']['output']>;
  emptyMessage?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GalleryPageFilter = {
  galleryHeading?: InputMaybe<StringFilter>;
  galleryDetail?: InputMaybe<StringFilter>;
  emptyMessage?: InputMaybe<StringFilter>;
};

export type GalleryPageConnectionEdges = {
  __typename?: 'GalleryPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<GalleryPage>;
};

export type GalleryPageConnection = Connection & {
  __typename?: 'GalleryPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GalleryPageConnectionEdges>>>;
};

export type SiteSocial = {
  __typename?: 'SiteSocial';
  facebook?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  youtube?: Maybe<Scalars['String']['output']>;
};

export type SiteSeoHome = {
  __typename?: 'SiteSeoHome';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SiteSeo = {
  __typename?: 'SiteSeo';
  defaultTitle?: Maybe<Scalars['String']['output']>;
  defaultDescription?: Maybe<Scalars['String']['output']>;
  home?: Maybe<SiteSeoHome>;
};

export type SiteErrorsGeneric = {
  __typename?: 'SiteErrorsGeneric';
  title?: Maybe<Scalars['String']['output']>;
  message?: Maybe<Scalars['String']['output']>;
  button?: Maybe<Scalars['String']['output']>;
};

export type SiteErrorsGallery = {
  __typename?: 'SiteErrorsGallery';
  title?: Maybe<Scalars['String']['output']>;
  message?: Maybe<Scalars['String']['output']>;
  button?: Maybe<Scalars['String']['output']>;
};

export type SiteErrors = {
  __typename?: 'SiteErrors';
  generic?: Maybe<SiteErrorsGeneric>;
  gallery?: Maybe<SiteErrorsGallery>;
};

export type SiteDefaults = {
  __typename?: 'SiteDefaults';
  galleryHeading?: Maybe<Scalars['String']['output']>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  address?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  social?: Maybe<SiteSocial>;
  seo?: Maybe<SiteSeo>;
  errors?: Maybe<SiteErrors>;
  defaults?: Maybe<SiteDefaults>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSocialFilter = {
  facebook?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  youtube?: InputMaybe<StringFilter>;
};

export type SiteSeoHomeFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SiteSeoFilter = {
  defaultTitle?: InputMaybe<StringFilter>;
  defaultDescription?: InputMaybe<StringFilter>;
  home?: InputMaybe<SiteSeoHomeFilter>;
};

export type SiteErrorsGenericFilter = {
  title?: InputMaybe<StringFilter>;
  message?: InputMaybe<StringFilter>;
  button?: InputMaybe<StringFilter>;
};

export type SiteErrorsGalleryFilter = {
  title?: InputMaybe<StringFilter>;
  message?: InputMaybe<StringFilter>;
  button?: InputMaybe<StringFilter>;
};

export type SiteErrorsFilter = {
  generic?: InputMaybe<SiteErrorsGenericFilter>;
  gallery?: InputMaybe<SiteErrorsGalleryFilter>;
};

export type SiteDefaultsFilter = {
  galleryHeading?: InputMaybe<StringFilter>;
};

export type SiteFilter = {
  address?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  social?: InputMaybe<SiteSocialFilter>;
  seo?: InputMaybe<SiteSeoFilter>;
  errors?: InputMaybe<SiteErrorsFilter>;
  defaults?: InputMaybe<SiteDefaultsFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type NavTopLevelLinks = {
  __typename?: 'NavTopLevelLinks';
  href?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type NavAccommodationLinks = {
  __typename?: 'NavAccommodationLinks';
  href?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type NavAdventureLinks = {
  __typename?: 'NavAdventureLinks';
  href?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type Nav = Node & Document & {
  __typename?: 'Nav';
  topLevelLinks?: Maybe<Array<Maybe<NavTopLevelLinks>>>;
  accommodationLinks?: Maybe<Array<Maybe<NavAccommodationLinks>>>;
  adventureLinks?: Maybe<Array<Maybe<NavAdventureLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NavTopLevelLinksFilter = {
  href?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type NavAccommodationLinksFilter = {
  href?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type NavAdventureLinksFilter = {
  href?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type NavFilter = {
  topLevelLinks?: InputMaybe<NavTopLevelLinksFilter>;
  accommodationLinks?: InputMaybe<NavAccommodationLinksFilter>;
  adventureLinks?: InputMaybe<NavAdventureLinksFilter>;
};

export type NavConnectionEdges = {
  __typename?: 'NavConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Nav>;
};

export type NavConnection = Connection & {
  __typename?: 'NavConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NavConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateAccommodation: Accommodation;
  createAccommodation: Accommodation;
  updateAdventures: Adventures;
  createAdventures: Adventures;
  updateListingPages: ListingPages;
  createListingPages: ListingPages;
  updateContactPage: ContactPage;
  createContactPage: ContactPage;
  updateGalleryPage: GalleryPage;
  createGalleryPage: GalleryPage;
  updateSite: Site;
  createSite: Site;
  updateNav: Nav;
  createNav: Nav;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateAccommodationArgs = {
  relativePath: Scalars['String']['input'];
  params: AccommodationMutation;
};


export type MutationCreateAccommodationArgs = {
  relativePath: Scalars['String']['input'];
  params: AccommodationMutation;
};


export type MutationUpdateAdventuresArgs = {
  relativePath: Scalars['String']['input'];
  params: AdventuresMutation;
};


export type MutationCreateAdventuresArgs = {
  relativePath: Scalars['String']['input'];
  params: AdventuresMutation;
};


export type MutationUpdateListingPagesArgs = {
  relativePath: Scalars['String']['input'];
  params: ListingPagesMutation;
};


export type MutationCreateListingPagesArgs = {
  relativePath: Scalars['String']['input'];
  params: ListingPagesMutation;
};


export type MutationUpdateContactPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactPageMutation;
};


export type MutationCreateContactPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactPageMutation;
};


export type MutationUpdateGalleryPageArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryPageMutation;
};


export type MutationCreateGalleryPageArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryPageMutation;
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateNavArgs = {
  relativePath: Scalars['String']['input'];
  params: NavMutation;
};


export type MutationCreateNavArgs = {
  relativePath: Scalars['String']['input'];
  params: NavMutation;
};

export type DocumentUpdateMutation = {
  accommodation?: InputMaybe<AccommodationMutation>;
  adventures?: InputMaybe<AdventuresMutation>;
  listingPages?: InputMaybe<ListingPagesMutation>;
  contactPage?: InputMaybe<ContactPageMutation>;
  galleryPage?: InputMaybe<GalleryPageMutation>;
  site?: InputMaybe<SiteMutation>;
  nav?: InputMaybe<NavMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  accommodation?: InputMaybe<AccommodationMutation>;
  adventures?: InputMaybe<AdventuresMutation>;
  listingPages?: InputMaybe<ListingPagesMutation>;
  contactPage?: InputMaybe<ContactPageMutation>;
  galleryPage?: InputMaybe<GalleryPageMutation>;
  site?: InputMaybe<SiteMutation>;
  nav?: InputMaybe<NavMutation>;
};

export type AccommodationHeroMutation = {
  mobileSrc?: InputMaybe<Scalars['String']['input']>;
  desktopSrc?: InputMaybe<Scalars['String']['input']>;
};

export type AccommodationGalleryMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  fullSize?: InputMaybe<Scalars['String']['input']>;
};

export type AccommodationInfoSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  align?: InputMaybe<Scalars['String']['input']>;
};

export type AccommodationCtaButtonMutation = {
  href?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type AccommodationCtaMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<AccommodationCtaButtonMutation>;
};

export type AccommodationMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<AccommodationHeroMutation>;
  gallery?: InputMaybe<Array<InputMaybe<AccommodationGalleryMutation>>>;
  imagesPerPage?: InputMaybe<Scalars['Float']['input']>;
  cardImage?: InputMaybe<Scalars['String']['input']>;
  cardMobileImage?: InputMaybe<Scalars['String']['input']>;
  cardDescription?: InputMaybe<Scalars['String']['input']>;
  cardFeatures?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  showBookNow?: InputMaybe<Scalars['Boolean']['input']>;
  infoSections?: InputMaybe<Array<InputMaybe<AccommodationInfoSectionsMutation>>>;
  cta?: InputMaybe<AccommodationCtaMutation>;
};

export type AdventuresHeroMutation = {
  mobileSrc?: InputMaybe<Scalars['String']['input']>;
  desktopSrc?: InputMaybe<Scalars['String']['input']>;
};

export type AdventuresGalleryMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  fullSize?: InputMaybe<Scalars['String']['input']>;
};

export type AdventuresInfoSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  align?: InputMaybe<Scalars['String']['input']>;
};

export type AdventuresCtaButtonMutation = {
  href?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type AdventuresCtaMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<AdventuresCtaButtonMutation>;
};

export type AdventuresMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<AdventuresHeroMutation>;
  gallery?: InputMaybe<Array<InputMaybe<AdventuresGalleryMutation>>>;
  imagesPerPage?: InputMaybe<Scalars['Float']['input']>;
  cardImage?: InputMaybe<Scalars['String']['input']>;
  cardMobileImage?: InputMaybe<Scalars['String']['input']>;
  cardDescription?: InputMaybe<Scalars['String']['input']>;
  cardFeatures?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  infoSections?: InputMaybe<Array<InputMaybe<AdventuresInfoSectionsMutation>>>;
  cta?: InputMaybe<AdventuresCtaMutation>;
};

export type ListingPagesHeroMutation = {
  mobileSrc?: InputMaybe<Scalars['String']['input']>;
  desktopSrc?: InputMaybe<Scalars['String']['input']>;
};

export type ListingPagesItemsBlocksTitleMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type ListingPagesItemsBlocksTextMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type ListingPagesItemsBlocksSubheadingMutation = {
  content?: InputMaybe<Scalars['String']['input']>;
};

export type ListingPagesItemsBlocksListMutation = {
  contentItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ListingPagesItemsBlocksMutation = {
  title?: InputMaybe<ListingPagesItemsBlocksTitleMutation>;
  text?: InputMaybe<ListingPagesItemsBlocksTextMutation>;
  subheading?: InputMaybe<ListingPagesItemsBlocksSubheadingMutation>;
  list?: InputMaybe<ListingPagesItemsBlocksListMutation>;
};

export type ListingPagesItemsMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<ListingPagesItemsBlocksMutation>>>;
};

export type ListingPagesInfoSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  align?: InputMaybe<Scalars['String']['input']>;
};

export type ListingPagesCtaButtonMutation = {
  href?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type ListingPagesCtaMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<ListingPagesCtaButtonMutation>;
};

export type ListingPagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<ListingPagesHeroMutation>;
  items?: InputMaybe<Array<InputMaybe<ListingPagesItemsMutation>>>;
  columns?: InputMaybe<Scalars['Float']['input']>;
  showBookNow?: InputMaybe<Scalars['Boolean']['input']>;
  infoSections?: InputMaybe<Array<InputMaybe<ListingPagesInfoSectionsMutation>>>;
  cta?: InputMaybe<ListingPagesCtaMutation>;
  footnote?: InputMaybe<Scalars['String']['input']>;
  galleryHeading?: InputMaybe<Scalars['String']['input']>;
};

export type ContactPageInfoSectionsMutation = {
  sectionTitle?: InputMaybe<Scalars['String']['input']>;
  sectionsItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ContactPageFormFieldsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['String']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ContactPageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  mobileSrc?: InputMaybe<Scalars['String']['input']>;
  desktopSrc?: InputMaybe<Scalars['String']['input']>;
  infoHeading?: InputMaybe<Scalars['String']['input']>;
  infoSections?: InputMaybe<Array<InputMaybe<ContactPageInfoSectionsMutation>>>;
  formHeading?: InputMaybe<Scalars['String']['input']>;
  formFields?: InputMaybe<Array<InputMaybe<ContactPageFormFieldsMutation>>>;
  formSubmitLabel?: InputMaybe<Scalars['String']['input']>;
};

export type GalleryPageMutation = {
  galleryHeading?: InputMaybe<Scalars['String']['input']>;
  galleryDetail?: InputMaybe<Scalars['String']['input']>;
  emptyMessage?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSocialMutation = {
  facebook?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  youtube?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSeoHomeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSeoMutation = {
  defaultTitle?: InputMaybe<Scalars['String']['input']>;
  defaultDescription?: InputMaybe<Scalars['String']['input']>;
  home?: InputMaybe<SiteSeoHomeMutation>;
};

export type SiteErrorsGenericMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  message?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<Scalars['String']['input']>;
};

export type SiteErrorsGalleryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  message?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<Scalars['String']['input']>;
};

export type SiteErrorsMutation = {
  generic?: InputMaybe<SiteErrorsGenericMutation>;
  gallery?: InputMaybe<SiteErrorsGalleryMutation>;
};

export type SiteDefaultsMutation = {
  galleryHeading?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  address?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  social?: InputMaybe<SiteSocialMutation>;
  seo?: InputMaybe<SiteSeoMutation>;
  errors?: InputMaybe<SiteErrorsMutation>;
  defaults?: InputMaybe<SiteDefaultsMutation>;
};

export type NavTopLevelLinksMutation = {
  href?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type NavAccommodationLinksMutation = {
  href?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type NavAdventureLinksMutation = {
  href?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type NavMutation = {
  topLevelLinks?: InputMaybe<Array<InputMaybe<NavTopLevelLinksMutation>>>;
  accommodationLinks?: InputMaybe<Array<InputMaybe<NavAccommodationLinksMutation>>>;
  adventureLinks?: InputMaybe<Array<InputMaybe<NavAdventureLinksMutation>>>;
};

export type AccommodationPartsFragment = { __typename: 'Accommodation', slug: string, title: string, description: string, imagesPerPage?: number | null, cardImage?: string | null, cardMobileImage?: string | null, cardDescription?: string | null, cardFeatures?: Array<string | null> | null, showBookNow?: boolean | null, hero?: { __typename: 'AccommodationHero', mobileSrc: string, desktopSrc: string } | null, gallery?: Array<{ __typename: 'AccommodationGallery', src?: string | null, alt?: string | null, fullSize?: string | null } | null> | null, infoSections?: Array<{ __typename: 'AccommodationInfoSections', heading: string, content?: Array<string | null> | null, align?: string | null } | null> | null, cta?: { __typename: 'AccommodationCta', heading: string, description?: string | null, button?: { __typename: 'AccommodationCtaButton', href?: string | null, label?: string | null } | null } | null };

export type AdventuresPartsFragment = { __typename: 'Adventures', slug: string, title: string, description: string, category?: string | null, imagesPerPage?: number | null, cardImage?: string | null, cardMobileImage?: string | null, cardDescription?: string | null, cardFeatures?: Array<string | null> | null, hero?: { __typename: 'AdventuresHero', mobileSrc: string, desktopSrc: string } | null, gallery?: Array<{ __typename: 'AdventuresGallery', src?: string | null, alt?: string | null, fullSize?: string | null } | null> | null, infoSections?: Array<{ __typename: 'AdventuresInfoSections', heading: string, content?: Array<string | null> | null, align?: string | null } | null> | null, cta?: { __typename: 'AdventuresCta', heading: string, description?: string | null, button?: { __typename: 'AdventuresCtaButton', href?: string | null, label?: string | null } | null } | null };

export type ListingPagesPartsFragment = { __typename: 'ListingPages', title: string, description?: string | null, columns?: number | null, showBookNow?: boolean | null, footnote?: string | null, galleryHeading?: string | null, hero?: { __typename: 'ListingPagesHero', mobileSrc: string, desktopSrc: string } | null, items?: Array<{ __typename: 'ListingPagesItems', image?: string | null, href?: string | null, blocks?: Array<{ __typename: 'ListingPagesItemsBlocksTitle', content?: string | null } | { __typename: 'ListingPagesItemsBlocksText', content?: string | null } | { __typename: 'ListingPagesItemsBlocksSubheading', content?: string | null } | { __typename: 'ListingPagesItemsBlocksList', contentItems?: Array<string | null> | null } | null> | null } | null> | null, infoSections?: Array<{ __typename: 'ListingPagesInfoSections', heading: string, content?: Array<string | null> | null, align?: string | null } | null> | null, cta?: { __typename: 'ListingPagesCta', heading: string, description?: string | null, button?: { __typename: 'ListingPagesCtaButton', href?: string | null, label?: string | null } | null } | null };

export type ContactPagePartsFragment = { __typename: 'ContactPage', title?: string | null, mobileSrc?: string | null, desktopSrc?: string | null, infoHeading?: string | null, formHeading?: string | null, formSubmitLabel?: string | null, infoSections?: Array<{ __typename: 'ContactPageInfoSections', sectionTitle?: string | null, sectionsItems?: Array<string | null> | null } | null> | null, formFields?: Array<{ __typename: 'ContactPageFormFields', name?: string | null, label?: string | null, type?: string | null, placeholder?: string | null, required?: boolean | null } | null> | null };

export type GalleryPagePartsFragment = { __typename: 'GalleryPage', galleryHeading?: string | null, galleryDetail?: string | null, emptyMessage?: string | null };

export type SitePartsFragment = { __typename: 'Site', address?: string | null, phone?: string | null, email?: string | null, social?: { __typename: 'SiteSocial', facebook?: string | null, instagram?: string | null, youtube?: string | null } | null, seo?: { __typename: 'SiteSeo', defaultTitle?: string | null, defaultDescription?: string | null, home?: { __typename: 'SiteSeoHome', title?: string | null, description?: string | null } | null } | null, errors?: { __typename: 'SiteErrors', generic?: { __typename: 'SiteErrorsGeneric', title?: string | null, message?: string | null, button?: string | null } | null, gallery?: { __typename: 'SiteErrorsGallery', title?: string | null, message?: string | null, button?: string | null } | null } | null, defaults?: { __typename: 'SiteDefaults', galleryHeading?: string | null } | null };

export type NavPartsFragment = { __typename: 'Nav', topLevelLinks?: Array<{ __typename: 'NavTopLevelLinks', href?: string | null, label?: string | null } | null> | null, accommodationLinks?: Array<{ __typename: 'NavAccommodationLinks', href?: string | null, label?: string | null } | null> | null, adventureLinks?: Array<{ __typename: 'NavAdventureLinks', href?: string | null, label?: string | null } | null> | null };

export type AccommodationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AccommodationQuery = { __typename?: 'Query', accommodation: { __typename: 'Accommodation', id: string, slug: string, title: string, description: string, imagesPerPage?: number | null, cardImage?: string | null, cardMobileImage?: string | null, cardDescription?: string | null, cardFeatures?: Array<string | null> | null, showBookNow?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AccommodationHero', mobileSrc: string, desktopSrc: string } | null, gallery?: Array<{ __typename: 'AccommodationGallery', src?: string | null, alt?: string | null, fullSize?: string | null } | null> | null, infoSections?: Array<{ __typename: 'AccommodationInfoSections', heading: string, content?: Array<string | null> | null, align?: string | null } | null> | null, cta?: { __typename: 'AccommodationCta', heading: string, description?: string | null, button?: { __typename: 'AccommodationCtaButton', href?: string | null, label?: string | null } | null } | null } };

export type AccommodationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AccommodationFilter>;
}>;


export type AccommodationConnectionQuery = { __typename?: 'Query', accommodationConnection: { __typename?: 'AccommodationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AccommodationConnectionEdges', cursor: string, node?: { __typename: 'Accommodation', id: string, slug: string, title: string, description: string, imagesPerPage?: number | null, cardImage?: string | null, cardMobileImage?: string | null, cardDescription?: string | null, cardFeatures?: Array<string | null> | null, showBookNow?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AccommodationHero', mobileSrc: string, desktopSrc: string } | null, gallery?: Array<{ __typename: 'AccommodationGallery', src?: string | null, alt?: string | null, fullSize?: string | null } | null> | null, infoSections?: Array<{ __typename: 'AccommodationInfoSections', heading: string, content?: Array<string | null> | null, align?: string | null } | null> | null, cta?: { __typename: 'AccommodationCta', heading: string, description?: string | null, button?: { __typename: 'AccommodationCtaButton', href?: string | null, label?: string | null } | null } | null } | null } | null> | null } };

export type AdventuresQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AdventuresQuery = { __typename?: 'Query', adventures: { __typename: 'Adventures', id: string, slug: string, title: string, description: string, category?: string | null, imagesPerPage?: number | null, cardImage?: string | null, cardMobileImage?: string | null, cardDescription?: string | null, cardFeatures?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AdventuresHero', mobileSrc: string, desktopSrc: string } | null, gallery?: Array<{ __typename: 'AdventuresGallery', src?: string | null, alt?: string | null, fullSize?: string | null } | null> | null, infoSections?: Array<{ __typename: 'AdventuresInfoSections', heading: string, content?: Array<string | null> | null, align?: string | null } | null> | null, cta?: { __typename: 'AdventuresCta', heading: string, description?: string | null, button?: { __typename: 'AdventuresCtaButton', href?: string | null, label?: string | null } | null } | null } };

export type AdventuresConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AdventuresFilter>;
}>;


export type AdventuresConnectionQuery = { __typename?: 'Query', adventuresConnection: { __typename?: 'AdventuresConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AdventuresConnectionEdges', cursor: string, node?: { __typename: 'Adventures', id: string, slug: string, title: string, description: string, category?: string | null, imagesPerPage?: number | null, cardImage?: string | null, cardMobileImage?: string | null, cardDescription?: string | null, cardFeatures?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AdventuresHero', mobileSrc: string, desktopSrc: string } | null, gallery?: Array<{ __typename: 'AdventuresGallery', src?: string | null, alt?: string | null, fullSize?: string | null } | null> | null, infoSections?: Array<{ __typename: 'AdventuresInfoSections', heading: string, content?: Array<string | null> | null, align?: string | null } | null> | null, cta?: { __typename: 'AdventuresCta', heading: string, description?: string | null, button?: { __typename: 'AdventuresCtaButton', href?: string | null, label?: string | null } | null } | null } | null } | null> | null } };

export type ListingPagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ListingPagesQuery = { __typename?: 'Query', listingPages: { __typename: 'ListingPages', id: string, title: string, description?: string | null, columns?: number | null, showBookNow?: boolean | null, footnote?: string | null, galleryHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ListingPagesHero', mobileSrc: string, desktopSrc: string } | null, items?: Array<{ __typename: 'ListingPagesItems', image?: string | null, href?: string | null, blocks?: Array<{ __typename: 'ListingPagesItemsBlocksTitle', content?: string | null } | { __typename: 'ListingPagesItemsBlocksText', content?: string | null } | { __typename: 'ListingPagesItemsBlocksSubheading', content?: string | null } | { __typename: 'ListingPagesItemsBlocksList', contentItems?: Array<string | null> | null } | null> | null } | null> | null, infoSections?: Array<{ __typename: 'ListingPagesInfoSections', heading: string, content?: Array<string | null> | null, align?: string | null } | null> | null, cta?: { __typename: 'ListingPagesCta', heading: string, description?: string | null, button?: { __typename: 'ListingPagesCtaButton', href?: string | null, label?: string | null } | null } | null } };

export type ListingPagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ListingPagesFilter>;
}>;


export type ListingPagesConnectionQuery = { __typename?: 'Query', listingPagesConnection: { __typename?: 'ListingPagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ListingPagesConnectionEdges', cursor: string, node?: { __typename: 'ListingPages', id: string, title: string, description?: string | null, columns?: number | null, showBookNow?: boolean | null, footnote?: string | null, galleryHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ListingPagesHero', mobileSrc: string, desktopSrc: string } | null, items?: Array<{ __typename: 'ListingPagesItems', image?: string | null, href?: string | null, blocks?: Array<{ __typename: 'ListingPagesItemsBlocksTitle', content?: string | null } | { __typename: 'ListingPagesItemsBlocksText', content?: string | null } | { __typename: 'ListingPagesItemsBlocksSubheading', content?: string | null } | { __typename: 'ListingPagesItemsBlocksList', contentItems?: Array<string | null> | null } | null> | null } | null> | null, infoSections?: Array<{ __typename: 'ListingPagesInfoSections', heading: string, content?: Array<string | null> | null, align?: string | null } | null> | null, cta?: { __typename: 'ListingPagesCta', heading: string, description?: string | null, button?: { __typename: 'ListingPagesCtaButton', href?: string | null, label?: string | null } | null } | null } | null } | null> | null } };

export type ContactPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactPageQuery = { __typename?: 'Query', contactPage: { __typename: 'ContactPage', id: string, title?: string | null, mobileSrc?: string | null, desktopSrc?: string | null, infoHeading?: string | null, formHeading?: string | null, formSubmitLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, infoSections?: Array<{ __typename: 'ContactPageInfoSections', sectionTitle?: string | null, sectionsItems?: Array<string | null> | null } | null> | null, formFields?: Array<{ __typename: 'ContactPageFormFields', name?: string | null, label?: string | null, type?: string | null, placeholder?: string | null, required?: boolean | null } | null> | null } };

export type ContactPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactPageFilter>;
}>;


export type ContactPageConnectionQuery = { __typename?: 'Query', contactPageConnection: { __typename?: 'ContactPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactPageConnectionEdges', cursor: string, node?: { __typename: 'ContactPage', id: string, title?: string | null, mobileSrc?: string | null, desktopSrc?: string | null, infoHeading?: string | null, formHeading?: string | null, formSubmitLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, infoSections?: Array<{ __typename: 'ContactPageInfoSections', sectionTitle?: string | null, sectionsItems?: Array<string | null> | null } | null> | null, formFields?: Array<{ __typename: 'ContactPageFormFields', name?: string | null, label?: string | null, type?: string | null, placeholder?: string | null, required?: boolean | null } | null> | null } | null } | null> | null } };

export type GalleryPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GalleryPageQuery = { __typename?: 'Query', galleryPage: { __typename: 'GalleryPage', id: string, galleryHeading?: string | null, galleryDetail?: string | null, emptyMessage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GalleryPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryPageFilter>;
}>;


export type GalleryPageConnectionQuery = { __typename?: 'Query', galleryPageConnection: { __typename?: 'GalleryPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GalleryPageConnectionEdges', cursor: string, node?: { __typename: 'GalleryPage', id: string, galleryHeading?: string | null, galleryDetail?: string | null, emptyMessage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, address?: string | null, phone?: string | null, email?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: { __typename: 'SiteSocial', facebook?: string | null, instagram?: string | null, youtube?: string | null } | null, seo?: { __typename: 'SiteSeo', defaultTitle?: string | null, defaultDescription?: string | null, home?: { __typename: 'SiteSeoHome', title?: string | null, description?: string | null } | null } | null, errors?: { __typename: 'SiteErrors', generic?: { __typename: 'SiteErrorsGeneric', title?: string | null, message?: string | null, button?: string | null } | null, gallery?: { __typename: 'SiteErrorsGallery', title?: string | null, message?: string | null, button?: string | null } | null } | null, defaults?: { __typename: 'SiteDefaults', galleryHeading?: string | null } | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, address?: string | null, phone?: string | null, email?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: { __typename: 'SiteSocial', facebook?: string | null, instagram?: string | null, youtube?: string | null } | null, seo?: { __typename: 'SiteSeo', defaultTitle?: string | null, defaultDescription?: string | null, home?: { __typename: 'SiteSeoHome', title?: string | null, description?: string | null } | null } | null, errors?: { __typename: 'SiteErrors', generic?: { __typename: 'SiteErrorsGeneric', title?: string | null, message?: string | null, button?: string | null } | null, gallery?: { __typename: 'SiteErrorsGallery', title?: string | null, message?: string | null, button?: string | null } | null } | null, defaults?: { __typename: 'SiteDefaults', galleryHeading?: string | null } | null } | null } | null> | null } };

export type NavQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NavQuery = { __typename?: 'Query', nav: { __typename: 'Nav', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, topLevelLinks?: Array<{ __typename: 'NavTopLevelLinks', href?: string | null, label?: string | null } | null> | null, accommodationLinks?: Array<{ __typename: 'NavAccommodationLinks', href?: string | null, label?: string | null } | null> | null, adventureLinks?: Array<{ __typename: 'NavAdventureLinks', href?: string | null, label?: string | null } | null> | null } };

export type NavConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavFilter>;
}>;


export type NavConnectionQuery = { __typename?: 'Query', navConnection: { __typename?: 'NavConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavConnectionEdges', cursor: string, node?: { __typename: 'Nav', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, topLevelLinks?: Array<{ __typename: 'NavTopLevelLinks', href?: string | null, label?: string | null } | null> | null, accommodationLinks?: Array<{ __typename: 'NavAccommodationLinks', href?: string | null, label?: string | null } | null> | null, adventureLinks?: Array<{ __typename: 'NavAdventureLinks', href?: string | null, label?: string | null } | null> | null } | null } | null> | null } };

export const AccommodationPartsFragmentDoc = gql`
    fragment AccommodationParts on Accommodation {
  __typename
  slug
  title
  description
  hero {
    __typename
    mobileSrc
    desktopSrc
  }
  gallery {
    __typename
    src
    alt
    fullSize
  }
  imagesPerPage
  cardImage
  cardMobileImage
  cardDescription
  cardFeatures
  showBookNow
  infoSections {
    __typename
    heading
    content
    align
  }
  cta {
    __typename
    heading
    description
    button {
      __typename
      href
      label
    }
  }
}
    `;
export const AdventuresPartsFragmentDoc = gql`
    fragment AdventuresParts on Adventures {
  __typename
  slug
  title
  description
  category
  hero {
    __typename
    mobileSrc
    desktopSrc
  }
  gallery {
    __typename
    src
    alt
    fullSize
  }
  imagesPerPage
  cardImage
  cardMobileImage
  cardDescription
  cardFeatures
  infoSections {
    __typename
    heading
    content
    align
  }
  cta {
    __typename
    heading
    description
    button {
      __typename
      href
      label
    }
  }
}
    `;
export const ListingPagesPartsFragmentDoc = gql`
    fragment ListingPagesParts on ListingPages {
  __typename
  title
  description
  hero {
    __typename
    mobileSrc
    desktopSrc
  }
  items {
    __typename
    image
    href
    blocks {
      __typename
      ... on ListingPagesItemsBlocksTitle {
        content
      }
      ... on ListingPagesItemsBlocksText {
        content
      }
      ... on ListingPagesItemsBlocksSubheading {
        content
      }
      ... on ListingPagesItemsBlocksList {
        contentItems
      }
    }
  }
  columns
  showBookNow
  infoSections {
    __typename
    heading
    content
    align
  }
  cta {
    __typename
    heading
    description
    button {
      __typename
      href
      label
    }
  }
  footnote
  galleryHeading
}
    `;
export const ContactPagePartsFragmentDoc = gql`
    fragment ContactPageParts on ContactPage {
  __typename
  title
  mobileSrc
  desktopSrc
  infoHeading
  infoSections {
    __typename
    sectionTitle
    sectionsItems
  }
  formHeading
  formFields {
    __typename
    name
    label
    type
    placeholder
    required
  }
  formSubmitLabel
}
    `;
export const GalleryPagePartsFragmentDoc = gql`
    fragment GalleryPageParts on GalleryPage {
  __typename
  galleryHeading
  galleryDetail
  emptyMessage
}
    `;
export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  address
  phone
  email
  social {
    __typename
    facebook
    instagram
    youtube
  }
  seo {
    __typename
    defaultTitle
    defaultDescription
    home {
      __typename
      title
      description
    }
  }
  errors {
    __typename
    generic {
      __typename
      title
      message
      button
    }
    gallery {
      __typename
      title
      message
      button
    }
  }
  defaults {
    __typename
    galleryHeading
  }
}
    `;
export const NavPartsFragmentDoc = gql`
    fragment NavParts on Nav {
  __typename
  topLevelLinks {
    __typename
    href
    label
  }
  accommodationLinks {
    __typename
    href
    label
  }
  adventureLinks {
    __typename
    href
    label
  }
}
    `;
export const AccommodationDocument = gql`
    query accommodation($relativePath: String!) {
  accommodation(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AccommodationParts
  }
}
    ${AccommodationPartsFragmentDoc}`;
export const AccommodationConnectionDocument = gql`
    query accommodationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AccommodationFilter) {
  accommodationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AccommodationParts
      }
    }
  }
}
    ${AccommodationPartsFragmentDoc}`;
export const AdventuresDocument = gql`
    query adventures($relativePath: String!) {
  adventures(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AdventuresParts
  }
}
    ${AdventuresPartsFragmentDoc}`;
export const AdventuresConnectionDocument = gql`
    query adventuresConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AdventuresFilter) {
  adventuresConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AdventuresParts
      }
    }
  }
}
    ${AdventuresPartsFragmentDoc}`;
export const ListingPagesDocument = gql`
    query listingPages($relativePath: String!) {
  listingPages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ListingPagesParts
  }
}
    ${ListingPagesPartsFragmentDoc}`;
export const ListingPagesConnectionDocument = gql`
    query listingPagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ListingPagesFilter) {
  listingPagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ListingPagesParts
      }
    }
  }
}
    ${ListingPagesPartsFragmentDoc}`;
export const ContactPageDocument = gql`
    query contactPage($relativePath: String!) {
  contactPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactPageParts
  }
}
    ${ContactPagePartsFragmentDoc}`;
export const ContactPageConnectionDocument = gql`
    query contactPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactPageFilter) {
  contactPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactPageParts
      }
    }
  }
}
    ${ContactPagePartsFragmentDoc}`;
export const GalleryPageDocument = gql`
    query galleryPage($relativePath: String!) {
  galleryPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GalleryPageParts
  }
}
    ${GalleryPagePartsFragmentDoc}`;
export const GalleryPageConnectionDocument = gql`
    query galleryPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GalleryPageFilter) {
  galleryPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GalleryPageParts
      }
    }
  }
}
    ${GalleryPagePartsFragmentDoc}`;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const NavDocument = gql`
    query nav($relativePath: String!) {
  nav(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavParts
  }
}
    ${NavPartsFragmentDoc}`;
export const NavConnectionDocument = gql`
    query navConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavFilter) {
  navConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavParts
      }
    }
  }
}
    ${NavPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      accommodation(variables: AccommodationQueryVariables, options?: C): Promise<{data: AccommodationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AccommodationQueryVariables, query: string}> {
        return requester<{data: AccommodationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AccommodationQueryVariables, query: string}, AccommodationQueryVariables>(AccommodationDocument, variables, options);
      },
    accommodationConnection(variables?: AccommodationConnectionQueryVariables, options?: C): Promise<{data: AccommodationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AccommodationConnectionQueryVariables, query: string}> {
        return requester<{data: AccommodationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AccommodationConnectionQueryVariables, query: string}, AccommodationConnectionQueryVariables>(AccommodationConnectionDocument, variables, options);
      },
    adventures(variables: AdventuresQueryVariables, options?: C): Promise<{data: AdventuresQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AdventuresQueryVariables, query: string}> {
        return requester<{data: AdventuresQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AdventuresQueryVariables, query: string}, AdventuresQueryVariables>(AdventuresDocument, variables, options);
      },
    adventuresConnection(variables?: AdventuresConnectionQueryVariables, options?: C): Promise<{data: AdventuresConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AdventuresConnectionQueryVariables, query: string}> {
        return requester<{data: AdventuresConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AdventuresConnectionQueryVariables, query: string}, AdventuresConnectionQueryVariables>(AdventuresConnectionDocument, variables, options);
      },
    listingPages(variables: ListingPagesQueryVariables, options?: C): Promise<{data: ListingPagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ListingPagesQueryVariables, query: string}> {
        return requester<{data: ListingPagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ListingPagesQueryVariables, query: string}, ListingPagesQueryVariables>(ListingPagesDocument, variables, options);
      },
    listingPagesConnection(variables?: ListingPagesConnectionQueryVariables, options?: C): Promise<{data: ListingPagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ListingPagesConnectionQueryVariables, query: string}> {
        return requester<{data: ListingPagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ListingPagesConnectionQueryVariables, query: string}, ListingPagesConnectionQueryVariables>(ListingPagesConnectionDocument, variables, options);
      },
    contactPage(variables: ContactPageQueryVariables, options?: C): Promise<{data: ContactPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageQueryVariables, query: string}> {
        return requester<{data: ContactPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageQueryVariables, query: string}, ContactPageQueryVariables>(ContactPageDocument, variables, options);
      },
    contactPageConnection(variables?: ContactPageConnectionQueryVariables, options?: C): Promise<{data: ContactPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageConnectionQueryVariables, query: string}> {
        return requester<{data: ContactPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageConnectionQueryVariables, query: string}, ContactPageConnectionQueryVariables>(ContactPageConnectionDocument, variables, options);
      },
    galleryPage(variables: GalleryPageQueryVariables, options?: C): Promise<{data: GalleryPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryPageQueryVariables, query: string}> {
        return requester<{data: GalleryPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryPageQueryVariables, query: string}, GalleryPageQueryVariables>(GalleryPageDocument, variables, options);
      },
    galleryPageConnection(variables?: GalleryPageConnectionQueryVariables, options?: C): Promise<{data: GalleryPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryPageConnectionQueryVariables, query: string}> {
        return requester<{data: GalleryPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryPageConnectionQueryVariables, query: string}, GalleryPageConnectionQueryVariables>(GalleryPageConnectionDocument, variables, options);
      },
    site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    nav(variables: NavQueryVariables, options?: C): Promise<{data: NavQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavQueryVariables, query: string}> {
        return requester<{data: NavQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavQueryVariables, query: string}, NavQueryVariables>(NavDocument, variables, options);
      },
    navConnection(variables?: NavConnectionQueryVariables, options?: C): Promise<{data: NavConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavConnectionQueryVariables, query: string}> {
        return requester<{data: NavConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavConnectionQueryVariables, query: string}, NavConnectionQueryVariables>(NavConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  